# Generated by Django 5.1.6 on 2026-08-16 17:46

import django.db.models.deletion
import storage.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='исходное имя')),
                ('file', models.FileField(upload_to=storage.models.user_file_upload_path, verbose_name='файл')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='размер')),
                ('comment', models.TextField(blank=True, default='', verbose_name='комментарий')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='дата загрузки')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='дата последнего скачивания')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='токен публичной ссылки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_files', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
